var affirmations = [
  { id: 0, message: "I am worthy of love and kindness", isFavorite: false },
  { id: 1, message: "My possibilities are endless", isFavorite: false },
  { id: 2, message: "I radiate confidence, self-respect, and inner harmony", isFavorite: false },
  { id: 3, message: "I am a beacon of positivity and attract good things into my life", isFavorite: false },
  { id: 4, message: "I am deserving of success and embrace the abundance coming my way", isFavorite: false },
  { id: 5, message: "Today, I choose joy and peace", isFavorite: false },
  { id: 6, message: "I am a magnet for positive energy, and I attract positivity effortlessly", isFavorite: false },
  { id: 7, message: "I am resilient, strong, and capable of overcoming any challenge", isFavorite: false },
  { id: 8, message: "I trust in my abilities and believe in my unique gifts", isFavorite: false },
  { id: 9, message: "My life is filled with purpose, passion, and prosperity", isFavorite: false },
  { id: 10, message: "I am surrounded by love and support", isFavorite: false },
  { id: 11, message: "I release all negativity and embrace a positive mindset", isFavorite: false },
  { id: 12, message: "I am a source of inspiration for others", isFavorite: false },
  { id: 13, message: "I am in control of my thoughts, and I choose positivity", isFavorite: false },
  { id: 14, message: "I am creating a life filled with love, happiness, and success", isFavorite: false },
  { id: 15, message: "I am a powerful creator; I create the life I want and enjoy it", isFavorite: false },
  { id: 16, message: "I am at peace with all that has happened, is happening, and will happen", isFavorite: false },
  { id: 17, message: "I am constantly evolving and growing into the best version of myself", isFavorite: false },
  { id: 18, message: "I attract positive, like-minded individuals into my life", isFavorite: false },
  { id: 19, message: "I am grateful for the abundance of blessings in my life", isFavorite: false },
];

var mantras = [
  { id: 0, message: "Embrace the journey, not just the destination", isFavorite: false },
  { id: 1, message: "Today is a gift; that's why they call it the present", isFavorite: false },
  { id: 2, message: "I am resilient, and I can handle whatever comes my way", isFavorite: false },
  { id: 3, message: "Progress, not perfection", isFavorite: false },
  { id: 4, message: "My potential is limitless", isFavorite: false },
  { id: 5, message: "Inhale confidence, exhale doubt", isFavorite: false },
  { id: 6, message: "I am the architect of my own destiny", isFavorite: false },
  { id: 7, message: "Every challenge is an opportunity for growth", isFavorite: false },
  { id: 8, message: "I choose joy in every moment", isFavorite: false },
  { id: 9, message: "I am deserving of success and happiness", isFavorite: false },
  { id: 10, message: "My mind is a powerful tool; I choose positive thoughts", isFavorite: false },
  { id: 11, message: "I attract positivity and abundance into my life", isFavorite: false },
  { id: 12, message: "Small steps lead to big results", isFavorite: false },
  { id: 13, message: "I am a work in progress, and that's okay", isFavorite: false },
  { id: 14, message: "I am the CEO of my life; I make empowered decisions", isFavorite: false },
  { id: 15, message: "Today, I choose courage over fear", isFavorite: false },
  { id: 16, message: "I radiate love and compassion to myself and others", isFavorite: false },
  { id: 17, message: "I am in control of how I react to situations; I choose peace", isFavorite: false },
  { id: 18, message: "I trust in the process of life", isFavorite: false },
  { id: 19, message: "I am grateful for the present moment; it is my greatest gift", isFavorite: false },
];
