var affirmations = [
  "I am worthy of love and kindness",
  "My possibilities are endless",
  "I radiate confidence, self-respect, and inner harmony",
  "I am a beacon of positivity and attract good things into my life",
  "I am deserving of success and embrace the abundance coming my way",
  "Today, I choose joy and peace",
  "I am a magnet for positive energy, and I attract positivity effortlessly",
  "I am resilient, strong, and capable of overcoming any challenge",
  "I trust in my abilities and believe in my unique gifts",
  "My life is filled with purpose, passion, and prosperity",
  "I am surrounded by love and support",
  "I release all negativity and embrace a positive mindset",
  "I am a source of inspiration for others",
  "I am in control of my thoughts, and I choose positivity",
  "I am creating a life filled with love, happiness, and success",
  "I am a powerful creator; I create the life I want and enjoy it",
  "I am at peace with all that has happened, is happening, and will happen",
  "I am constantly evolving and growing into the best version of myself",
  "I attract positive, like-minded individuals into my life",
  "I am grateful for the abundance of blessings in my life",
];

var mantras = [
  "Embrace the journey, not just the destination",
  "Today is a gift; that's why they call it the present",
  "I am resilient, and I can handle whatever comes my way",
  "Progress, not perfection",
  "My potential is limitless",
  "Inhale confidence, exhale doubt",
  "I am the architect of my own destiny",
  "Every challenge is an opportunity for growth",
  "I choose joy in every moment",
  "I am deserving of success and happiness",
  "My mind is a powerful tool; I choose positive thoughts",
  "I attract positivity and abundance into my life",
  "Small steps lead to big results",
  "I am a work in progress, and that's okay",
  "I am the CEO of my life; I make empowered decisions",
  "Today, I choose courage over fear",
  "I radiate love and compassion to myself and others",
  "I am in control of how I react to situations; I choose peace",
  "I trust in the process of life",
  "I am grateful for the present moment; it is my greatest gift",
];
